//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonAksesuar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int SiparisID { get; set; }
        public string SiparisOzet { get; set; }
        public Nullable<int> UyeID { get; set; }
        public string Tarih { get; set; }
        public string Adres { get; set; }
        public string Durum { get; set; }
        public Nullable<int> Fiyat { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
    }
}
