//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonAksesuar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelefonAksesuar.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Paneli.
        /// </summary>
        public static string AdminPaneli {
            get {
                return ResourceManager.GetString("AdminPaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Ara {
            get {
                return ResourceManager.GetString("Ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string BeniHatırla {
            get {
                return ResourceManager.GetString("BeniHatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Çıkış {
            get {
                return ResourceManager.GetString("Çıkış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string Fiyat {
            get {
                return ResourceManager.GetString("Fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı Kargo!.
        /// </summary>
        public static string HızlıKargo {
            get {
                return ResourceManager.GetString("HızlıKargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş verdiğiniz günden itibaren 5 iş günü içerisinde ürünleriniz size ulaşır..
        /// </summary>
        public static string HızlıKargoAciklama {
            get {
                return ResourceManager.GetString("HızlıKargoAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldin.
        /// </summary>
        public static string Hoşgeldin {
            get {
                return ResourceManager.GetString("Hoşgeldin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İade Seçeneği !.
        /// </summary>
        public static string İadeSecenegi {
            get {
                return ResourceManager.GetString("İadeSecenegi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünü beğenmezseniz veya ürün hasarlı çıkarsa 1 hafta içerisinde başka bir ürünle değiştirebilirsiniz.
        /// </summary>
        public static string İadeSecenegiAciklama {
            get {
                return ResourceManager.GetString("İadeSecenegiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string İletişim {
            get {
                return ResourceManager.GetString("İletişim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaliteli ve şık.
        /// </summary>
        public static string KaliteliVeŞık {
            get {
                return ResourceManager.GetString("KaliteliVeŞık", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapıda Ödeme !.
        /// </summary>
        public static string KapıdaOdeme {
            get {
                return ResourceManager.GetString("KapıdaOdeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi kartı,havale vs. gibi ödemeler yok! Ürününüz kapınıza gelsin ödemeyi yapın!.
        /// </summary>
        public static string KapıdaOdemeAciklama {
            get {
                return ResourceManager.GetString("KapıdaOdemeAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kılıflar.
        /// </summary>
        public static string Kılıflar {
            get {
                return ResourceManager.GetString("Kılıflar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kulaklıklar.
        /// </summary>
        public static string Kulaklıklar {
            get {
                return ResourceManager.GetString("Kulaklıklar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string KullanıcıAdı {
            get {
                return ResourceManager.GetString("KullanıcıAdı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TL.
        /// </summary>
        public static string ParaBirimi {
            get {
                return ResourceManager.GetString("ParaBirimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilim.
        /// </summary>
        public static string Profilim {
            get {
                return ResourceManager.GetString("Profilim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şarj Cihazları.
        /// </summary>
        public static string ŞarjCihazları {
            get {
                return ResourceManager.GetString("ŞarjCihazları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string Sehir {
            get {
                return ResourceManager.GetString("Sehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetim.
        /// </summary>
        public static string Sepetim {
            get {
                return ResourceManager.GetString("Sepetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişlerim.
        /// </summary>
        public static string Siparişlerim {
            get {
                return ResourceManager.GetString("Siparişlerim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string Soyad {
            get {
                return ResourceManager.GetString("Soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Detayı.
        /// </summary>
        public static string UrunDetayı {
            get {
                return ResourceManager.GetString("UrunDetayı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün ismi.
        /// </summary>
        public static string UrunIsmi {
            get {
                return ResourceManager.GetString("UrunIsmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string Ürünler {
            get {
                return ResourceManager.GetString("Ürünler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string UyeOl {
            get {
                return ResourceManager.GetString("UyeOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaş.
        /// </summary>
        public static string Yas {
            get {
                return ResourceManager.GetString("Yas", resourceCulture);
            }
        }
    }
}
